// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chirps.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const chirpCreate = `-- name: ChirpCreate :one
INSERT INTO chirps (id, created_at, updated_at, body, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, body, user_id
`

type ChirpCreateParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) ChirpCreate(ctx context.Context, arg ChirpCreateParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, chirpCreate, arg.Body, arg.UserID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const chirpsGet = `-- name: ChirpsGet :one
Select id, created_at, updated_at, body, user_id from chirps
WHERE id = $1
`

func (q *Queries) ChirpsGet(ctx context.Context, id uuid.UUID) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, chirpsGet, id)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const chirpsList = `-- name: ChirpsList :many
SELECT id, created_at, updated_at, body, user_id from chirps
ORDER BY created_at ASC
`

func (q *Queries) ChirpsList(ctx context.Context) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, chirpsList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
